version: '3.8'

services:
  EcommerceApi:
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:ApplicationConnection=Server=sqlServer,1433;User=sa;Password=francis.123;Database=EcommerceDb;MultipleActiveResultSets=True;
    volumes:
      - ~/AppData/Roaming/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro