version: '3.8'

services:

  sqlServer:
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=francis.123
    container_name: sqlServer
    image: mcr.microsoft.com/mssql/server:2022-latest

  EcommerceApi:
    ports:
      - 5200:80
    depends_on:
      - sqlServer
    image: ecommerce:v7